### ISSUE TITLE
Feature request: Connect via SSL

### ISSUE THREAD

**Issue by marcosflobo** [micronaut-projects/micronaut-nats#37]
This a feature request to be able to connect to NAT Server via SSL.

This feature is documented here https://docs.nats.io/developing-with-nats/security/tls

### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Using the application.yaml file, fill the properties to connect with TLS

### Expected Behaviour

The client is able to connect to the NATS servier with TLS

### Actual Behaviour

Today, there is no a way to enable the SSL connectivity

### Environment Information

- **Operating System**: All
- **Micronaut Version:** 1.3.x 2.x
- **JDK Version:** As much as possible

### Example Application

- https://docs.nats.io/developing-with-nats/security/tls

**Comment by grimmjo** [comment]
Hi @marcosflobo,

thanks for your feature request. I think it's already implemented, I will just provide you an example here and add some documentation for this.

**Comment by marcosflobo** [comment]
That would be great @grimmjo, it's important for a production use case. Thank you in advance for the example

**Comment by grimmjo** [comment]
So I've fixes various problems with ssl/tls. Now it's working correctly.

Here is a short example how to configure the ssl/tls:
```yaml
nats:
  addresses:
    - "nats://localhost:4222" 
  tls:
    trust-store-path:  /path/to/client.truststore.jks 
    trust-store-password: secret
    certificate-path: /path/to/certificate.crt 
```

Currently I'm not allowed to merge PRs anymore. When this is fixed and/or the pr is merged, the fix will be available in the snapshort version. Have a look at https://docs.micronaut.io/latest/guide/appendix.html#usingsnapshots 

The current snapshot version is: `1.0.1.BUILD-SNAPSHOT`
